"use client";

import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { BookOpen, ShieldCheck, Rocket, PlugZap } from "lucide-react";

const FEATURES = [
  {
    icon: BookOpen,
    title: "Integrated Management of AAS Templates",
    paragraphs: [
      "The repository consolidates all AAS templates (types) developed domestically into a single, unified storage system.",
      "Users can create various AAS instances using standardized templates and populate them with the required data to easily build and utilize compliant digital twins for manufacturing.",
    ],
  },
  {
    icon: ShieldCheck,
    title: "Compliance with International Standards",
    paragraphs: [
      "The system restricts the creation of non-compliant AAS instances and only supports versions that adhere to the official AAS standard.",
      "It automatically verifies compliance with the latest AAS Metamodel Specification (Version 3.0), allowing only validated instances to be registered and distributed.",
      "Compatibility with standard templates defined by the IDTA (Industrial Digital Twin Association) is verified to ensure high reliability and interoperability of the AAS-based digital twins.",
    ],
  },
  {
    icon: Rocket,
    title: "Simplified AAS Instance Creation and Deployment",
    paragraphs: [
      "AAS instances can be automatically generated by simply inputting real asset data into pre-registered templates.",
      "The created instances can be immediately deployed and run on the repository server, enabling real-time integration into active manufacturing systems.",
    ],
  },
  {
    icon: PlugZap,
    title: "Scalability through API Support",
    paragraphs: [
      "A standardized RESTful API is provided, enabling external systems to query and retrieve AAS template and instance data.",
      "Flexible integration with external platforms and manufacturing IT systems is supported, ensuring high scalability and ecosystem compatibility for AAS-based digital twin applications.",
    ],
  },
];

export default function About() {
  return (
    <div>
      {/* Toolbar */}
      <div className="py-4 border-b mb-8">
        <div className="container-xxl mx-auto px-4">
          <h1 className="text-lg font-bold text-foreground">About</h1>
          <nav className="text-xs text-muted-foreground flex gap-1 mt-0.5">
            <Link href="/" className="hover:text-foreground">Home</Link>
            <span>/</span>
            <span>About</span>
          </nav>
        </div>
      </div>

      {/* Content */}
      <div className="container-xxl mx-auto px-4 pb-16 space-y-12">
        {/* Hero */}
        <div className="text-center space-y-2">
          <h2 className="text-3xl font-bold text-foreground tracking-tight">About</h2>
          <p className="text-muted-foreground font-semibold">ezAAS Model Hub</p>
        </div>

        {/* Video */}
        <div className="rounded-xl overflow-hidden border shadow-sm aspect-video max-w-3xl mx-auto">
          <iframe
            className="w-full h-full"
            src="https://www.youtube.com/embed/n4IDBR2C1CY?si=jvDaO89Su0huplNn"
            allowFullScreen
            title="ezAAS Model Hub Introduction"
          />
        </div>

        <Separator />

        {/* Features heading */}
        <div className="text-center">
          <h3 className="text-2xl font-bold text-foreground">Key Features and Benefits</h3>
        </div>

        {/* Feature cards */}
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {FEATURES.map(({ icon: Icon, title, paragraphs }) => (
            <Card key={title} className="flex flex-col h-full">
              <CardHeader className="pb-2">
                <div className="flex items-center gap-2 mb-1">
                  <div className="rounded-md bg-primary/10 p-2">
                    <Icon className="size-4 text-primary" />
                  </div>
                </div>
                <CardTitle className="text-sm leading-snug">{title}</CardTitle>
              </CardHeader>
              <CardContent className="flex-1 space-y-3">
                {paragraphs.map((p, i) => (
                  <p key={i} className="text-sm text-muted-foreground leading-relaxed">{p}</p>
                ))}
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
