# 초기 설정 - SSL 인증서 발급용
server {
    listen       80;
    server_name  dream.a2lab.ai localhost;

    charset utf-8;
    
    # Certbot 인증을 위한 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    # 정적 파일 서빙
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
}
